### ISSUE TITLE
KeyError: 'shape' when loading frozen tensorflow model with uff.from_tensorflow_frozen_model()

### ISSUE THREAD

**Issue by mawah** [ladisk/pyuff#11]
Hi folks,

I hope I've come to the right place, as I'm not sure whom to ask about this problem. Feel free to redirect me.

All of the following was done inside of NVIDIA's TensorRT 18.02-py2 docker container, in which I pip installed the tensorflow-gpu 1.7.0 package. I downloaded the TensorFlow models git repo and followed a tf-slim example to retrain a ResNet v1 50 model for a new classification task. I then froze the model, creating [this .pb file](https://fpgastorage.blob.core.windows.net/v100/tfslim/research/slim/retrained_models/frozen_model.pb). I tried to load this file in TensorRT using [this script](https://fpgastorage.blob.core.windows.net/v100/tfslim/research/slim/score_with_retrained_tfslim_resnet50.py) but got the following error message, apparently during conversion from TF -> UFF:

```
Traceback (most recent call last):
  File "score_with_retrained_tfslim_resnet50.py", line 123, in <module>
    output_file=output_file)
  File "score_with_retrained_tfslim_resnet50.py", line 75, in main
    engine = Engine(**network)
  File "/usr/lib/python2.7/dist-packages/tensorrt/lite/engine.py", line 171, in __init__
    modelstream = uff.from_tensorflow_frozen_model(path, output_nodes)
  File "/opt/uff/uff/converters/tensorflow/conversion_helpers.py", line 103, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, **kwargs)
  File "/opt/uff/uff/converters/tensorflow/conversion_helpers.py", line 75, in from_tensorflow
    name="main")
  File "/opt/uff/uff/converters/tensorflow/converter.py", line 64, in convert_tf2uff_graph
    uff_graph, input_replacements)
  File "/opt/uff/uff/converters/tensorflow/converter.py", line 51, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes)
  File "/opt/uff/uff/converters/tensorflow/converter.py", line 28, in convert_layer
    fields = cls.parse_tf_attrs(tf_node.attr)
  File "/opt/uff/uff/converters/tensorflow/converter.py", line 177, in parse_tf_attrs
    for key, val in attrs.items()}
  File "/opt/uff/uff/converters/tensorflow/converter.py", line 177, in <dictcomp>
    for key, val in attrs.items()}
  File "/opt/uff/uff/converters/tensorflow/converter.py", line 172, in parse_tf_attr_value
    return cls.convert_tf2uff_field(code, val)
  File "/opt/uff/uff/converters/tensorflow/converter.py", line 157, in convert_tf2uff_field
    'type': 'dtype', 'list': 'list'}[code]
KeyError: 'shape'
```

I am unsure how to interpret this error or what can be done to correct it. Is anyone here able to help, or recommend what should be investigated further? Thanks in advance!

**Comment by Aashit-Sharma** [comment]
@jankoslavic thanks for the info but how do you resolve this ? I too am getting this error.

**Comment by Aashit-Sharma** [comment]
@mawah , I am getting the same error. were you able to resolve it ?

**Comment by jankoslavic** [comment]
this package pyUFF has nothing to do with tensorflow

**Comment by Aashit-Sharma** [comment]
yeah , I realized that and rectified my comment. 
Can't find this error anywhere else
